### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by LeMutique** [AntonMu/TrainYourOwnYOLO#121]
#49 # System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow version (use command below)**: v1.15.0-92-g5d80e1e8e6 1.15.2
- **CUDA/cuDNN version**: 
- **GPU model and memory**:
- **Exact command to reproduce**: python Detector.py

### Describe the problem
Hey, I had a lot of issues during installation but finally manage to get things working. The example with cats works without issues. But as soon as I train my own data and try out the Detetor.py script it returns the followinf error: 
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,42] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,42], [18,1024,1,1].

### Source code / logs
(env) C:\Users\me\Documents\TrainYourOwnYOLO\3_Inference>python Detector.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:186: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0430 16:33:10.165201  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0430 16:33:10.196469  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:199: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

W0430 16:33:10.196469  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:206: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

W0430 16:33:10.212090  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

W0430 16:33:10.243336  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0430 16:33:13.758637  1812 module_wrapper.py:139] From C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

Traceback (most recent call last):
  File "C:\Users\me\Documents\TrainYourOwnYOLO\2_Training\src\keras_yolo3\yolo.py", line 72, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,42] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,42], [18,1024,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Detector.py", line 179, in <module>
    "model_image_size": (416, 416),
  File "C:\Users\me\Documents\TrainYourOwnYOLO\2_Training\src\keras_yolo3\yolo.py", line 46, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "C:\Users\me\Documents\TrainYourOwnYOLO\2_Training\src\keras_yolo3\yolo.py", line 84, in generate
    self.model_path
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\ops\variables.py", line 2067, in assign
    self._variable, value, use_locking=use_locking, name=name)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 65, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1770, in __init__
    control_input_ops)
  File "C:\Users\me\Documents\TrainYourOwnYOLO\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,42] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,42], [18,1024,1,1].

**Comment by adafranca** [comment]
Did you find a solution for this problem ? I have the same problem
