### ISSUE TITLE
AssertionError: class id must be less than num_classes

### ISSUE THREAD

**Issue by NotYourGal** [AntonMu/TrainYourOwnYOLO#131]
After setting up I am getting the following issue:

Traceback (most recent call last):
  File "Train_YOLO.py", line 217, in <module>
    callbacks=[logging, checkpoint],
  File "C:\Users\PriyaN\miniconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\PriyaN\miniconda3\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\PriyaN\miniconda3\lib\site-packages\keras\engine\training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\PriyaN\miniconda3\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\Users\PriyaN\AppData\Roaming\Python\Python37\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\PriyaN\miniconda3\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\PriyaN\TrainYourOwnYOLO\Utils\Train_Utils.py", line 200, in data_generator
    y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)
  File "C:\Users\PriyaN\TrainYourOwnYOLO\2_Training\src\keras_yolo3\yolo3\model.py", line 290, in preprocess_true_boxes
    ).all(), "class id must be less than num_classes"
AssertionError: class id must be less than num_classes

How do I resolve this?

**Comment by robisen1** [comment]
Did you add any classes to data_classes.txt or data_train.txt ? This happens when there is a mismatch between labels and class id. For example if you have classes bat, cat, hat the id's should be 0,1,2. If, for example, the class classes file got changed by deletion or addition you will get this error. Same if there are more id's in the data_train.txt

**Comment by NotYourGal** [comment]
IThere is nothing in the data_classes.txt
but i have not deleted anything from data_train.txt

**Comment by NotYourGal** [comment]
Okay I updated the data_classes file and it's training. Thanks

**Comment by robisen1** [comment]
> Okay I updated the data_classes file and it's training. Thanks

Glad to hear
