### ISSUE TITLE
Error from train.py

### ISSUE THREAD

**Issue by sudhir002** [AntonMu/TrainYourOwnYOLO#158]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/PYTHON__/YoloV3/TrainYourOwnYOLO-master/2_Training/Train_YOLO.py", line 191, in <module>
    "yolo_loss": lambda y_true, y_pred: y_pred
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 446, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1592, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1652, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\losses.py", line 220, in call
    y_pred, y_true)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\losses\util.py", line 79, in squeeze_or_expand_dimensions
    is_last_dim_1 = math_ops.equal(1, array_ops.shape(y_pred)[-1])
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 898, in _slice_helper
    name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1064, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 9535, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1786, in __init__
    control_input_ops)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index -1 of dimension 0 out of bounds. for 'loss/yolo_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.

Process finished with exit code 1

**Comment by sudhir002** [comment]
Got the solution

**Comment by bushra-hafeez** [comment]
Hey, I am getting valueError while running the training script but it is a little different.
ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/Adam/Adam/conv2d_59/kernel/m/Initializer/zeros:0' shape=(1, 1, 1024, 30) dtype=float32>

Do you know how to solve this?

**Comment by sudhir002** [comment]
> Hey, I am getting valueError while running the training script but it is a little different.
> ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/Adam/Adam/conv2d_59/kernel/m/Initializer/zeros:0' shape=(1, 1, 1024, 30) dtype=float32>
> 
> Do you know how to solve this?

Have you tried with same requirements which here mentioned?

**Comment by omar16100** [comment]
@sudhir002 How did you get the solution?

Can you please clarify?

**Comment by sudhir002** [comment]
> @sudhir002 How did you get the solution?
> 
> Can you please clarify?

Compare your installed library version with requirements.txt . 

Just install package with requirements.txt it will work.
