### ISSUE TITLE
Missing yolo.h5

### ISSUE THREAD

**Issue by Floo33R** [AntonMu/TrainYourOwnYOLO#174]
# System information
- **~/Documents/yolo/TrainYourOwnYOLO/2_Training**
- **POP-OS 20.04**:

## The problem
When I'm using `python Download_and_Convert_YOLO_weights.py` there is no yolo.h5 file created. So, when I'm using the command `python Train_YOLO.py` there is the error-message as following:

Traceback (most recent call last):
  File "Train_YOLO.py", line 173, in <module>
    model = create_model(
  File "/home/pop/Documents/yolo/TrainYourOwnYOLO/Utils/Train_Utils.py", line 94, in create_model
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
  File "/home/pop/Documents/yolo/TrainYourOwnYOLO/env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2204, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/home/pop/Documents/yolo/TrainYourOwnYOLO/env/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/pop/Documents/yolo/TrainYourOwnYOLO/env/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/pop/Documents/yolo/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

When I'm trying to download the yolov3.weights and convert them manual with `python3 convert.py yolov3.cfg yolov3.weights model_data/yolo.h5` I'm getting the following error:

2020-09-07 11:59:32.963938: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Loading weights.
Traceback (most recent call last):
  File "convert.py", line 286, in <module>
    _main(parser.parse_args())
  File "convert.py", line 86, in _main
    major, minor, revision = np.ndarray(
TypeError: buffer is too small for requested array

How do i get the yolo.h5 file? What am I doing wrong?

**Comment by khaledhasanzami** [comment]
Any solution here?
