### ISSUE TITLE
tiny yolo training issue

### ISSUE THREAD

**Issue by jamslaugh** [AntonMu/TrainYourOwnYOLO#175]
### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section?

Once you are familiar with the code, you're welcome to modify it. Please only continue to file a bug report if you encounter an issue with the provided code and after having followed the instructions.

If you have followed the instructions exactly, couldn't solve your problem with the provided troubleshooting tips and would still like to file a bug or make a feature requests please follow the steps below.

1. It must be a bug, a feature request, or a significant problem with the documentation (for small docs fixes please send a PR instead).
2. **Every section** of the form below must be filled out.

------------------------

### Readme 

- I have followed all Readme instructions carefully word by word: yes

### System information
- **What is the top-level directory of the model you are using**: /content
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux from Colab
- **TensorFlow version (use command below)**: 2.3
- **CUDA/cuDNN version**: Colab one, standard
- **GPU model and memory**: Nvidia Tesla P100
- **Exact command to reproduce**: python Train_YOLO.py --is_tiny

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
Hi,

first of all, thank you for the efforts put in this project 😄 .

I am trying to train the tiny yolo version of the network to then convert it in tflite.

However, when I start python Train_YOLO.py --is_tiny on a two classes model, the following error comes out.

Can you please help me? I am pretty sure there is a missing step, just unable to sort it out.

Thanks in advance.

### Source code / logs

`Using TensorFlow backend.
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-09-09 18:13:28.759013: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-09 18:13:28.796730: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.797294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2020-09-09 18:13:28.797543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 18:13:28.799115: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-09 18:13:28.800824: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-09 18:13:28.801145: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-09 18:13:28.802929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-09 18:13:28.804015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-09 18:13:28.807690: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 18:13:28.807792: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.808370: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.808866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-09-09 18:13:28.813918: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-09-09 18:13:28.814101: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1676a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-09 18:13:28.814128: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-09 18:13:28.924747: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.925421: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1676bc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-09 18:13:28.925451: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-09-09 18:13:28.925606: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.926115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2020-09-09 18:13:28.926171: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 18:13:28.926192: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-09 18:13:28.926212: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-09 18:13:28.926232: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-09 18:13:28.926264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-09 18:13:28.926283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-09 18:13:28.926302: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 18:13:28.926373: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.926906: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.927400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-09-09 18:13:28.927471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 18:13:28.928414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-09 18:13:28.928440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2020-09-09 18:13:28.928452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2020-09-09 18:13:28.928562: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.929089: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 18:13:28.929612: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-09-09 18:13:28.929651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14221 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Create Tiny YOLOv3 model with 9 anchors and 2 classes.
/tensorflow-1.15.2/python3.6/keras/engine/saving.py:1319: UserWarning: Skipping loading of weights for layer conv2d_10 due to mismatch in shape ((1, 1, 512, 28) vs (255, 512, 1, 1)).
  weight_values[i].shape))
/tensorflow-1.15.2/python3.6/keras/engine/saving.py:1319: UserWarning: Skipping loading of weights for layer conv2d_10 due to mismatch in shape ((28,) vs (255,)).
  weight_values[i].shape))
/tensorflow-1.15.2/python3.6/keras/engine/saving.py:1319: UserWarning: Skipping loading of weights for layer conv2d_13 due to mismatch in shape ((1, 1, 256, 28) vs (255, 256, 1, 1)).
  weight_values[i].shape))
/tensorflow-1.15.2/python3.6/keras/engine/saving.py:1319: UserWarning: Skipping loading of weights for layer conv2d_13 due to mismatch in shape ((28,) vs (255,)).
  weight_values[i].shape))
Load weights /content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo-tiny.h5.
Freeze the first 42 layers of total 44 layers.
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 4 and 3 for 'yolo_loss/truediv_2' (op: 'RealDiv') with input shapes: [?,26,26,4,2], [3,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./TrainYourOwnYOLO/2_Training/Train_YOLO.py", line 157, in <module>
    input_shape, anchors, num_classes, freeze_body=2, weights_path=weights_path
  File "/content/TrainYourOwnYOLO/Utils/Train_Utils.py", line 178, in create_tiny_model
    )([*model_body.output, *y_true])
  File "/tensorflow-1.15.2/python3.6/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/tensorflow-1.15.2/python3.6/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 447, in yolo_loss
    y_true[l][..., 2:4] / anchors[anchor_mask[l]] * input_shape[::-1]
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/math_ops.py", line 912, in binary_op_wrapper
    return func(x, y, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/math_ops.py", line 1005, in _truediv_python3
    return gen_math_ops.real_div(x, y, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_math_ops.py", line 7954, in real_div
    "RealDiv", x=x, y=y, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 4 and 3 for 'yolo_loss/truediv_2' (op: 'RealDiv') with input shapes: [?,26,26,4,2], [3,2].`

**Comment by AntonMu** [comment]
Hi @jamslaugh,

I am glad you are enjoying it. I realize that the tiny model feature is not well documented. I made it a bit easier to use by defaulting everything to the tiny model if the `--is_tiny` flag is used. 

To use it you need to first download the tiny YOLO weights with:

```python Download_and_Convert_YOLO_weights.py --is_tiny```

and then train it with

```python Train_YOLO.py --is_tiny```

and finally run detection with

```python Detector.py --is_tiny```

Your error seems to come from trying to use the big YOLO weights, anchors and cfg but then trying to train it as a tiny model. It should be simpler to use with the latest update.

**Comment by jamslaugh** [comment]
Hi Anton,

Thank you for the answer, it worked like a charm. Moreover, with the last update you did, I can first use convert.py to convert the model from darknet weights and cfg and then use the Train_YOLO.py --is_tiny.

The issue is closed, however will come back in a few hours with another question, that maybe you can short answer here: will it ever be a compatibility for tflite fully quantized model? I am playing a bit with the convert.py file to create RELU-Only layers and wondered if it will ever be possible.

thank you in advance

**Comment by YannickLecroart** [comment]
I have redowloaded the source code to get the change you made to simplify the use of tiny yolo but when I use the command:

    python Download_and_Convert_YOLO_weights.py --is_tiny

I get the following error message: 

```
Loading weights.
Traceback (most recent call last):
  File "convert.py", line 286, in <module>
    _main(parser.parse_args())
  File "convert.py", line 87, in _main
    shape=(3,), dtype="int32", buffer=weights_file.read(12)
TypeError: buffer is too small for requested array
```
