### ISSUE TITLE
Not able to get this new version to work

### ISSUE THREAD

**Issue by DroopyKey** [AntonMu/TrainYourOwnYOLO#181]
Before filing a report consider the following two questions:

### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section? Yes

Once you are familiar with the code, you're welcome to modify it. Please only continue to file a bug report if you encounter an issue with the provided code and after having followed the instructions.

If you have followed the instructions exactly, couldn't solve your problem with the provided troubleshooting tips and would still like to file a bug or make a feature requests please follow the steps below.

1. It must be a bug, a feature request, or a significant problem with the documentation (for small docs fixes please send a PR instead).
2. **Every section** of the form below must be filled out.

------------------------

### Readme 

- I have followed all Readme instructions carefully: **Yes**

### Troubleshooting Section

- I have looked at the  [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section: **Yes**

### System information
- **C:\Users\user\Desktop\projectfolder\TrainYouOwnYOLO**:
- **Using Code downloaded from githhub with no modifications**:
- **Windows 10 Home x64**:
- **TensorFlow version as per requirements.txt version 2.3.0 installed in Anaconda environment with Python 3.7.9**:
- **CUDA/cuDNN version 10.1**:
- **GPU model GTX1050 Ti and memory 4G**:
- **Exact command to reproduce = Train_YOLO**:

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
First couple of Epoch's I get layout failed and remapper failed but then epochs run for a bit then sometimes terminate unexpectedly before the initial 51 are complete. The code then terminates once the layers are unlocked at Epoch 52.   

### Source code / logs
This is a copy of the last few lines I get when training terminates
2020-09-19 21:43:11.526081: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 1 Chunks of size 89031168 totalling 84.91MiB
2020-09-19 21:43:11.526107: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 1 Chunks of size 111445760 totalling 106.28MiB
2020-09-19 21:43:11.526131: I tensorflow/core/common_runtime/bfc_allocator.cc:1038] Sum Total of in-use chunks: 2.91GiB
2020-09-19 21:43:11.526158: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] total_region_allocated_bytes_: 3127299072 memory_limit_: 3127299278 available bytes: 206 curr_region_allocation_bytes_: 6254598656
2020-09-19 21:43:11.526193: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Stats:
Limit:                      3127299278
InUse:                      3122632960
MaxInUse:                   3127296768
NumAllocs:                      453053
MaxAllocSize:               1380319232
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2020-09-19 21:43:11.526306: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ****************************************************************************************************
2020-09-19 21:43:11.526347: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_input_ops.cc:461 : Resource exhausted: OOM when allocating tensor with shape[4,26,26,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "Train_YOLO.py", line 286, in <module>
    callbacks=[logging, checkpoint, reduce_lr, early_stopping],
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\function.py", line 550, in call
    ctx=ctx)
  File "C:\Users\User\anaconda3\envs\TrainYourOwnYOLONew\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[4,26,26,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradient_tape/functional_5/conv2d_66/Conv2D/Conv2DBackpropInput (defined at Train_YOLO.py:286) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_53394]

Function call stack:
train_function

2020-09-19 21:43:11.689720: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
2020-09-19 21:43:11.833786: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed

**Comment by AntonMu** [comment]
Hi @DroopyKey,

The problem is the your GPU memory is exhausted (out of memory error). In the second phase all layers are unfrozen and this it requires more memory. 4 GB is generally very small to do deep learning. Also, if you are using Windows, your GPU will already use resources to render your desktop graphics and other programs. So try to close all other open programs and check that your GPU memory is completely empty before running the training (you can check that in task manager). Alternatively, use Google Colab. 

Hope this helps!

**Comment by DroopyKey** [comment]
Thanks Anton.. yes I seem to be running out of GPU memory. I did however run it on Colab and while it runs to the end, there are still similar errors as I reported.

Here is the output from the first Epoch (these errors were not in the previous version of the code, which ran smoothly

Epoch 1/51
2020-09-20 02:51:29.966924: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:51:29.988433: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:51:30.167399: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:51:30.642550: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-20 02:51:35.302250: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-20 02:51:38.198587: W tensorflow/core/common_runtime/bfc_allocator.cc:312] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
1/2 [==============>...............] - ETA: 0s - loss: 11817.24122020-09-20 02:51:38.922673: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-09-20 02:51:39.773703: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
2020-09-20 02:51:39.803664: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 4553 callback api events and 4553 activity events. 
2/2 [==============================] - ETA: 0s - loss: 11258.78912020-09-20 02:51:44.168902: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:51:44.182886: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:51:44.309706: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2/2 [==============================] - 8s 4s/step - loss: 11258.7891 - val_loss: 9659.2480
Epoch 2/51
2/2 [==============================] - 7s 3s/step - loss: 9289.1641 - val_loss: 7818.2671
Epoch 3/51
2/2 [==============================] - 6s 3s/step - loss: 7530.4121 - val_loss: 6247.8892 

Error at Epoch 52

Unfreeze all layers.
Train on 90 samples, val on 10 samples, with batch size 4.
Epoch 52/102
2020-09-20 02:58:11.244267: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
 1/22 [>.............................] - ETA: 0s - loss: 176.66462020-09-20 02:58:13.852405: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-09-20 02:58:14.720766: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
2020-09-20 02:58:14.741377: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 3385 callback api events and 3385 activity events. 
22/22 [==============================] - ETA: 0s - loss: 66.68342020-09-20 02:58:25.898204: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:58:25.916615: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-09-20 02:58:26.074959: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
22/22 [==============================] - 13s 591ms/step - loss: 66.6834 - val_loss: 115.8330
Epoch 53/102
22/22 [==============================] - 10s 468ms/step - loss: 40.2419 - val_loss: 54.8650

and error at the end
Epoch 00092: early stopping
2020-09-20 03:05:46.100184: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

**Comment by AntonMu** [comment]
Hi - it looks good. Did you try running `Detector.py` and see if it works?

**Comment by DroopyKey** [comment]
Thank You… yes it runs fine
