### ISSUE TITLE
Error while running Train_YOLO.py file

### ISSUE THREAD

**Issue by akshattodi** [AntonMu/TrainYourOwnYOLO#216]
Before filing a report consider the following two questions:

### Have you followed all Readme instructions exactly? 
Yes

### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section? 
Yes

### Have you looked for [similar issues](https://github.com/AntonMu/TrainYourOwnYOLO/issues?q=is%3Aissue)? 
Yes

### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**:
- **System: Windows 10
- **TensorFlow version (use command below)**: 2.3.1
- **CUDA/cuDNN version**: 10.1/7.6.3
- **GPU model and memory**: MX150
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem

Sir I am facing the problems while running the Train_YOLO.py file. After installing all the requires models, libraries and setting all things correctly according to provided instructions then also it gives some error after running Trin_Yolo.py file so I can train the model so please give me the solution of this as soon as posible.

### Problem

2021-01-19 19:25:07.843470: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Stats:
Limit:                      1408043828
InUse:                      1147219200
MaxInUse:                   1147219456
NumAllocs:                        2137
MaxAllocSize:                708837376
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-01-19 19:25:07.845884: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ********************************_____***************************************************____________
2021-01-19 19:25:08.113307: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:947 : Resource exhausted: OOM when allocating tensor with shape[32,32,416,416] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "Train_YOLO.py", line 267, in <module>
    callbacks=frozen_callbacks,
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\integration\keras\keras.py", line 120, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 550, in call
    ctx=ctx)
  File "C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[32,32,416,416] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node functional_5/conv2d/Conv2D (defined at C:\Users\Akshat\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\integration\keras\keras.py:120) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_22034]

Function call stack:
train_function

2021-01-19 19:25:16.373648: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

**Comment by AntonMu** [comment]
#181

**Comment by akshattodi** [comment]
Thanks for your relay but I don't know that how can I make my GPU memory empty and I search it on internet and on youtube but I don't found any thing on it so can you please tell me how can I do this.

**Comment by akshattodi** [comment]
Sir I get the error while running Minimal_Example.py file.

2021-01-20 01:45:21.384221: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Users\Akshat\Desktop\TrainYourOwnYOLO-master\3_Inference\Detector.py", line 24, in <module>
    from utils import load_extractor_model, load_features, parse_input, detect_object
ImportError: cannot import name 'load_extractor_model'
Detected Cat Faces in 4.4 seconds

**Comment by akshattodi** [comment]
All issues are resolved and now its working perfectly, thanks.

**Comment by AntonMu** [comment]
Good to hear!

**Comment by akshattodi** [comment]
Sir how can I see its output on **opencv window** for real time object detection or for a recorded video with bounding box

**Comment by akshattodi** [comment]
Sir how to do the **real time object detection** in this  without using any picture or the saved videos

**Comment by akshattodi** [comment]
How to do  the webcam active?
