### ISSUE TITLE
Invalid argument while running Train_YOLO.py

### ISSUE THREAD

**Issue by Chethan187** [AntonMu/TrainYourOwnYOLO#229]
Facing issue while running Train_YOLO.py script. 

Error:
Traceback (most recent call last):
  File "Train_YOLO.py", line 256, in <module>
    history = model.fit_generator(
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1815, in fit_generator
    return self.fit(
  File "C:\Users\Chethan\test_yolo\lib\site-packages\wandb\integration\keras\keras.py", line 120, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1049, in fit
    data_handler = data_adapter.DataHandler(
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1105, in __init__
    self._adapter = adapter_cls(
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "C:\Users\Chethan\test_yolo\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 843, in _peek_and_restore
    peek = next(x)
  File "C:\Users\Chethan\Downloads\TrainYourOwnYOLO-master\TrainYourOwnYOLOmaster\Utils\Train_Utils.py", line 194, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "C:\Users\Chethan\Downloads\TrainYourOwnYOLO-master\TrainYourOwnYOLOmaster\2_Training\src\keras_yolo3\yolo3\utils.py", line 70, in get_random_data
    image = Image.open(line[0])
  File "C:\Users\Chethan\test_yolo\lib\site-packages\PIL\Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 22] Invalid argument: 'pid_3_F2_image_003_Ydir_30_rotation_PA115.png,261,363,50,387,Clip_New909_Top\n'

Kindly suggest.

**Comment by Chethan187** [comment]
Any update on this ?
