### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError

### ISSUE THREAD

**Issue by ha007-aman** [AntonMu/TrainYourOwnYOLO#235]
Readme
I have followed all Readme instructions carefully:Yes
Troubleshooting Section
I have looked at the troubleshooting section: Yes
Troubleshooting Section
I have looked for similar issues: Yes
System information
What is the top-level directory of the model you are using: I'm using Google Colab
Have I written custom code (as opposed to using a stock example script provided in the repo): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
TensorFlow version (use command below): 2.6.0
CUDA/cuDNN version: -
GPU model and memory: -
Exact command to reproduce:
You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.**

While testing the trained network with test images, I am getting following errors:

tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable conv2d_4/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_4/kernel)
	 [[{{node conv2d_4/Conv2D/ReadVariableOp}}]]
	 [[_arg_input_1_0_1/_2]]
  (1) Failed precondition: Could not find variable conv2d_4/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_4/kernel)
	 [[{{node conv2d_4/Conv2D/ReadVariableOp}}]]

Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Detector.py", line 245, in <module>
    postfix=FLAGS.postfix,
  File "/content/TrainYourOwnYOLO/Utils/utils.py", line 38, in detect_object
    prediction, new_image = yolo.detect_image(image)
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 162, in detect_image
    K.learning_phase(): 0,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable conv2d_4/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_4/kernel)
	 [[node conv2d_4/Conv2D/ReadVariableOp (defined at /content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py:21) ]]
	 [[_arg_input_1_0_1/_2]]
  (1) Failed precondition: Could not find variable conv2d_4/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_4/kernel)
	 [[node conv2d_4/Conv2D/ReadVariableOp (defined at /content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py:21) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv2d_4/Conv2D/ReadVariableOp':
  File "Detector.py", line 202, in <module>
    "model_image_size": (416, 416),
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 49, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 83, in generate
    Input(shape=(None, None, 3)), num_anchors // 3, num_classes
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 89, in yolo_body
    darknet = Model(inputs, darknet_body(inputs))
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 64, in darknet_body
    x = resblock_body(x, 128, 2)
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 50, in resblock_body
    x = DarknetConv2D_BN_Leaky(num_filters, (3, 3), strides=(2, 2))(x)
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py", line 21, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/content/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py", line 21, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer_v1.py", line 765, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1138, in convolution_v2
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1268, in convolution_internal
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 2722, in _conv2d_expanded_batch
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 973, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 522, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 2023, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 1421, in _dense_var_to_tensor
    return self.value()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 576, in value
    return self._read_variable_op()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 683, in _read_variable_op
    result = read_and_set_handle()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 674, in read_and_set_handle
    self.handle, self._dtype)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 485, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by AntonMu** [comment]
Hi @ha007-aman - I was unable to reproduce the problem. Can you explain the exact steps that led to your error?

Make sure you go to the [colab section](https://github.com/AntonMu/TrainYourOwnYOLO#google-colab-tutorial-) and click "Open in Colab". In colab, you can just hit "Run all" and everything should work as expected. 

Hope this helps.

**Comment by ha007-aman** [comment]
Thank you for the response. Yes, I have followed the same steps. Here is what I have done until now:

Following the steps, I trained YOLOv3 network for my dataset. While for testing I ran following commands: 

```
%cd /content/TrainYourOwnYOLO/3_Inference
!python Detector.py --input_path /content/drive/MyDrive/test --yolo_model /content/drive/MyDrive/log_directory/trained_weights_final.h5 --confidence 0.01 --no_save_img
```
It's just to run python file Detector.py. Usually I use the same command, but this time, it shows error. I couldn't understand, where the issue is.

**Comment by AntonMu** [comment]
Ok - it looks like you are doing some custom setup. That makes it hard to debug. 

My first intuition is that something went wrong with the training. 

I would recommend to fork the original repo and then replace the input files (images and annotations) and then run it as is. If that doesn't work, try to narrow down the cause with some minimale examples.

**Comment by ha007-aman** [comment]
Ok. I will test it out and post the update here.

**Comment by ha007-aman** [comment]
Yes AntonMu, your intuition was right. Something was wrong with the training. I just retrained the model and it worked fine.

Thank you.
