### ISSUE TITLE
Call initializer instance with the dtype argument instead of passing it to the constructor

### ISSUE THREAD

**Issue by poorneshwaran** [AntonMu/TrainYourOwnYOLO#238]
WARNING:tensorflow:From /home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "/home/metrics/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 75, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 209, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Detector.py", line 202, in <module>
    "model_image_size": (416, 416),
  File "/home/metrics/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 49, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/metrics/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 87, in generate
    self.model_path
  File "/home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/metrics/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 711, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

I utilized python=3.6, keras=2.4.3, tensorflow=1.14.0.

**Comment by poorneshwaran** [comment]
Hi, I follow the steps which you described. It's working fine when tf=2.4. I'm not sure what's the issue related to tf=1.14. please, help with this issue.

**Comment by poorneshwaran** [comment]
Hi, I resolved the issue. The issue which respect to h5py version. It's not loading the model which the version h5py>3. Now, I'm using the h5py=2.10.
