### ISSUE TITLE
Convert to YOLO format file error 

### ISSUE THREAD

**Issue by seba5496** [AntonMu/TrainYourOwnYOLO#39]
Hey, when i run de Convert_to_YOLO_format.py I get this

`Traceback (most recent call last):
  File "C:\Users\seba5\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Convert_to_YOLO_format.py", line 51, in <module>
    labels = multi_df['label'].unique()
  File "C:\Users\seba5\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\seba5\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'
 `

**Comment by AntonMu** [comment]
Hi Sebastian,

Thanks for the report. It looks like you are missing the label column in the [`Annotations-export.csv`]( https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/Data/Source_Images/Training_Images/vott-csv-export/Annotations-export.csv). Have you called your VoTT project "Annotations"? 

Also, please make sure that you use a virtual environment as described in the Readme.

Hope this helps!

Anton

**Comment by seba5496** [comment]
it worked! 
Thanks a lot, and sorry but i'm just starting in this world :)
thanks again

**Comment by AntonMu** [comment]
Glad to help! Good luck with the project. Feel free to post updates and share your results here. Thanks!
