### ISSUE TITLE
add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by sliawatimena** [AntonMu/TrainYourOwnYOLO#52]
My system is ubuntu 18.04, python 3.7.4, GPU, GTX 1080

$ python Minimal_Example.py
```
$ python Minimal_Example.py 
Detecting Cat Faces by calling: 

 python /media/suryadi/DATA/learn/TrainYourOwnYOLO/3_Inference/Detector.py --input_path /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Source_Images/Test_Images --classes /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Model_Weights/data_classes.txt --output /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Source_Images/Test_Image_Detection_Results --yolo_model /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Model_Weights/trained_weights_final.h5 --box_file /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Source_Images/Test_Image_Detection_Results/Detection_Results.csv --anchors /media/suryadi/DATA/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/model_data/yolo_anchors.txt --file_types .jpg .jpeg .png  

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W1210 11:12:24.056672 140496479233856 __init__.py:308] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1210 11:12:24.483830 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1210 11:12:24.483992 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1210 11:12:24.485436 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1210 11:12:24.500835 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W1210 11:12:24.500959 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W1210 11:12:24.872385 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

W1210 11:12:28.339353 140496479233856 deprecation_wrapper.py:119] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

/media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Model_Weights/trained_weights_final.h5 model, anchors, and classes loaded in 7.63sec.
W1210 11:12:32.294080 140496479233856 deprecation.py:323] From /media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Found 1 input labels: ['Cat_Face'] ...
Found 64 input images: ['04ebfcfd_fa70_4e49_84ff_66cf3c5c0407_best_cat_toys_for_older_cats_3.jpg', '0809_Cat_CNN.jpg', '0_Cat_research.jpg', '0_PAY_GRUMPY_CAT.jpg', '100.jpg'] ...
img_path =  /media/suryadi/DATA/learn/TrainYourOwnYOLO/Data/Source_Images/Test_Images/04ebfcfd_fa70_4e49_84ff_66cf3c5c0407_best_cat_toys_for_older_cats_3.jpg
image_data.shape =  (416, 416, 3)
Traceback (most recent call last):
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value batch_normalization_68/moving_variance
	 [[{{node batch_normalization_68/moving_variance/read}}]]
	 [[boolean_mask_1/GatherV2/_57]]
  (1) Failed precondition: Attempting to use uninitialized value batch_normalization_68/moving_variance
	 [[{{node batch_normalization_68/moving_variance/read}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/suryadi/DATA/learn/TrainYourOwnYOLO/3_Inference/Detector.py", line 176, in <module>
    prediction, image = detect_object(yolo, img_path, save_img = save_img, save_img_path = FLAGS.output, postfix=FLAGS.postfix)
  File "/media/suryadi/DATA/learn/TrainYourOwnYOLO/Utils/utils.py", line 40, in detect_object
    prediction, new_image = yolo.detect_image(image)
  File "/media/suryadi/DATA/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 127, in detect_image
    out_boxes, out_scores, out_classes = self.sess.run( [self.boxes, self.scores, self.classes], feed_dict={ self.yolo_model.input: image_data, self.input_image_shape: [image.size[1], image.size[0]], K.learning_phase(): 0 })
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/media/suryadi/DATA/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value batch_normalization_68/moving_variance
	 [[node batch_normalization_68/moving_variance/read (defined at /anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:402) ]]
	 [[boolean_mask_1/GatherV2/_57]]
  (1) Failed precondition: Attempting to use uninitialized value batch_normalization_68/moving_variance
	 [[node batch_normalization_68/moving_variance/read (defined at /anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:402) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'batch_normalization_68/moving_variance/read':
  File "/learn/TrainYourOwnYOLO/3_Inference/Detector.py", line 148, in <module>
    "model_image_size" : (416, 416),
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 47, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo.py", line 76, in generate
    if is_tiny_version else yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 85, in yolo_body
    x, y3 = make_last_layers(x, 128, num_anchors*(num_classes+5))
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/model.py", line 63, in make_last_layers
    DarknetConv2D_BN_Leaky(num_filters, (1,1)))(x)
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py", line 17, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py", line 17, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/learn/TrainYourOwnYOLO/2_Training/src/keras_yolo3/yolo3/utils.py", line 17, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  [Previous line repeated 3 more times]
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/layers/normalization.py", line 129, in build
    trainable=False)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/engine/base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2511, in default_variable_creator
    shape=shape)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1568, in __init__
    shape=shape)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1755, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 86, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4253, in identity
    "Identity", input=input, name=name)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/anaconda3/envs/yolo/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Detected Cat Faces in 11.2 seconds

```

Please help and thank you very much in advance.

Suryadi

**Comment by AntonMu** [comment]
Hi!

Try to start from scratch and follow all instructions from the Readme for
your OS. It has been tested on Ubuntu 18.04 and there should be no problem
as long as you replicate all the steps in the Readme.

Hope that helps!

**Comment by AntonMu** [comment]
I am closing this issue now. If you still encounter problems please file a new issue using the issue template. Thank you!
